Repository jiuliangut/earthquake-monitor, pull requests merged in 2024-12, with the labels that each got.

#37 Added transform
  .github/badges/pylint.svg
  pipeline/transform.py
  requirements.txt
Labels: enhancement

#38 made terraform folder
  terraform/README.md
  terraform/etl_pipeline.tf
  terraform/s3_bucket.tf
  terraform/variables.tf
Labels: enhancement

#39 #5-schema-fahad: Database Schema
  schema.sql
Labels: enhancement

#40 #16 extract tests
  .github/badges/test.svg
  pipeline/extract.py
  pipeline/test_extract.py
  requirements.txt
  test_extract.py
Labels: testing

#52 Added validation for key readings and logging
  .github/badges/pylint.svg
  pipeline/transform.py
Labels: enhancement, pipeline

#50 #9 seed database
  diagrams/erd.png
  schema.sql
Labels: enhancement

#49 #7 Updated main readme
  README.md
Labels: documentation

#57 Finished transform tests
  .github/badges/test.svg
  pipeline/test_transform.py
  pipeline/transform.py
  requirements.txt
Labels: testing, pipeline

#54 add terraform for ECRs
  terraform/dashboard_ecr.tf
  terraform/data_upload_ecr.tf
  terraform/etl_pipeline_ecr.tf
Labels: terraforming

#58 #22 load
  .github/badges/pylint.svg
  pipeline/load.py
  requirements.txt
Labels: enhancement, pipeline

#60 #24 load tests
  .github/badges/test.svg
  pipeline/test_load.py
Labels: testing, pipeline

#59 #6 plan api
  .github/badges/pylint.svg
  api/README.md
  api/api.py
Labels: documentation

#63 #61 update etl
  .github/badges/pylint.svg
  .github/badges/test.svg
  pipeline/extract.py
  pipeline/load.py
  pipeline/test_extract.py
  pipeline/test_load.py
  pipeline/test_transform.py
  pipeline/transform.py
Labels: enhancement, testing, pipeline

#62 Terraform readme + variables.tf updated
  terraform/README.md
  terraform/variables.tf
Labels: documentation, terraforming

#65 #53 deploy etl
  .github/badges/pylint.svg
  pipeline/Dockerfile
  pipeline/etl.py
  pipeline/load.py
  pipeline/requirements.txt
  pipeline/schema.sql
  terraform/etl_pipeline.tf
  terraform/variables.tf
Labels: terraforming, pipeline

#64 #5-schema
  pipeline/schema.sql
Labels: enhancement, schema

#70 added depth to erd and schema
  diagrams/erd.png
  pipeline/schema.sql
Labels: enhancement, schema

#72 Added wireframe png
  diagrams/Earthquake-dashboard-wireframe.png
Labels: diagram, dashboard

#75 #73 etl depth
  .github/badges/test.svg
  pipeline/extract.py
  pipeline/load.py
  pipeline/test_load.py
  pipeline/test_transform.py
  pipeline/transform.py
Labels: enhancement, pipeline

#78 Dashboard terraform
  .github/badges/pylint.svg
  terraform/dashboard_ecs.tf
  terraform/etl_pipeline.tf
  terraform/variables.tf
Labels: terraforming

#79 #36 pipeline readme
  .github/badges/pylint.svg
  pipeline/README.md
  pipeline/etl.py
Labels: documentation

#74 Added text to erd in readme
  README.md
Labels: documentation

#82 #42 preliminary lambda + scheduler for data_upload
  terraform/data_upload_lambda.tf
Labels: terraforming

#81 #41 Create API
  .github/badges/pylint.svg
  api/api.py
  api/database.py
Labels: enhancement, api

#80 #48 data upload script
  .github/badges/pylint.svg
  data_upload/README.md
  data_upload/extract.py
  requirements.txt
Labels: enhancement

#96 EC2 up and successfully connected
  .gitignore
  terraform/api_ec2.tf
  terraform/variables.tf
Labels: enhancement, terraforming

#95 fixed typo with decimal points for longitude
  data_upload/extract.py
Labels: bug

#94 #76 api tests
  .github/badges/pylint.svg
  .github/badges/test.svg
  api/test_api.py
  requirements.txt
Labels: testing

#99 #98 update api response
  api/database.py
Labels: enhancement

#103 Fixing lambda terraform
  terraform/data_upload_lambda.tf
  terraform/etl_pipeline.tf
Labels: bug, terraforming

#102 #100 build upload docker
  data_upload/extract.py
  terraform/data_upload_lambda.tf
Labels: terraforming, pipeline

#106 Push dev to main
  .github/badges/pylint.svg
  .github/badges/test.svg
  .gitignore
  api/api.py
  api/database.py
  api/test_api.py
  data_upload/Dockerfile
  data_upload/README.md
  data_upload/extract.py
  data_upload/requirements.txt
  requirements.txt
  terraform/api_ec2.tf
  terraform/data_upload_lambda.tf
  terraform/etl_pipeline.tf
  terraform/variables.tf
Labels: enhancement, pipeline, api

#107 #5- edited erd and schema
  diagrams/erd.png
  diagrams/erd_future.png
  pipeline/schema.sql
Labels: diagram, schema

#111 #91 sns script
  .github/badges/pylint.svg
  data_upload/extract.py
  notifications/notifications.py
Labels: enhancement

#110 #109 Added ingress for port 5000
  terraform/api_ec2.tf
Labels: bug, terraforming

#125 #17 dashboard
  .github/badges/pylint.svg
  dashboard/dashboard.py
  dashboard/db_queries.py
  dashboard/dockerfile
  dashboard/pages/subscribe.py
  dashboard/requirements.txt
Labels: dashboard

#127 #19 dockerise dashboard
  .github/badges/pylint.svg
  dashboard/dashboard.py
  dashboard/dockerfile
  dashboard/pages/subscribe.py
Labels: bug, dashboard

#126 #116 notifications lambda
  terraform/dashboard_ecr.tf
  terraform/data_upload_ecr.tf
  terraform/etl_pipeline_ecr.tf
  terraform/notification_ecr.tf
  terraform/notification_lambda.tf
  terraform/variables.tf
Labels: bug, terraforming

#129 #128-notification-readme
  api/README.md
  api/api.py
  dashboard/README.md
  notifications/README.md
Labels: documentation

#134 #47 create step function
  notifications/notifications.py
  pipeline/etl.py
  terraform/etl_pipeline.tf
  terraform/step_function.tf
Labels: bug, terraforming, pipeline

#133 updated data_upload script
  data_upload/extract.py
  data_upload/output/2024-12-02-data.pdf
Labels: pipeline

#139 Development
  .github/badges/pylint.svg
  README.md
  api/README.md
  api/api.py
  dashboard/README.md
  dashboard/dashboard.py
  dashboard/db_queries.py
  dashboard/dockerfile
  dashboard/pages/subscribe.py
  dashboard/requirements.txt
  data_upload/README.md
  data_upload/extract.py
  data_upload/output/2024-12-02-data.pdf
  diagrams/README.md
  diagrams/erd.png
  diagrams/erd_future.png
  notifications/README.md
  notifications/notifications.py
  pipeline/etl.py
  pipeline/schema.sql
  terraform/README.md
  terraform/api_ec2.tf
  terraform/dashboard_ecs.tf
  terraform/etl_pipeline.tf
  terraform/notification_lambda.tf
  terraform/step_function.tf
  terraform/variables.tf
Labels: enhancement, pipeline, dashboard

#144 Delete data_upload/output directory
  data_upload/output/2024-12-02-data.pdf
Labels: bug

#142 #132 test dashboard
  .github/badges/test.svg
  dashboard/test_db_queries.py
  pipeline/README.md
Labels: testing, dashboard

#159 #148 ml script
  .github/badges/pylint.svg
  api/model.py
  requirements.txt
Labels: enhancement, ML model

#162 #153-ml-api
  .github/badges/pylint.svg
  api/api.py
Labels: enhancement, api

#164 #153-ml-api
  api/api.py
Labels: bug, api

#165 Development
  .github/badges/pylint.svg
  .github/badges/test.svg
  api/api.py
  api/model.py
  dashboard/test_db_queries.py
  diagrams/architecture.png
  notifications/sns_topic_seeder.py
  pipeline/README.md
  requirements.txt
Labels: enhancement

#163 #157 updated terraform readme
  terraform/README.md
Labels: documentation

#167 Added subject to email warning
  notifications/notifications.py
Labels: enhancement

#168 #151-final-checks
  .github/badges/pylint.svg
  api/README.md
  dashboard/README.md
  data_upload/README.md
  notifications/README.md
  pipeline/README.md
Labels: documentation

#169 #151 Refined main and terraform readme
  README.md
  terraform/README.md
Labels: documentation

#171 #123 pdf title
  .github/badges/pylint.svg
  data_upload/extract.py
  data_upload/output/2024-12-02-data.pdf
Labels: documentation, enhancement

#170 #155 UI earthquake prediction
  dashboard/Overview.py
  dashboard/dockerfile
  dashboard/main_logo.png
  dashboard/pages/Magnitude_Predictor.py
  dashboard/pages/subscribe.py
  dashboard/requirements.txt
  dashboard/side_logo.png
Labels: enhancement, dashboard

#174 #st theme
  dashboard/.streamlit/config.toml
  dashboard/dockerfile
  dashboard/pages/Subscribe.py
Labels: enhancement, dashboard

#176 #123 pdf title
  .github/badges/pylint.svg
  data_upload/Dockerfile
  data_upload/extract.py
  data_upload/geovigil_logo.png
Labels: enhancement, pipeline
